# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_timeline_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
